#!/bin/bash
set -e

cargo build --release --features generate --locked --target-dir target
scripts/mkmo locale/
strip target/release/bah

tar --zstd -cf bah.tar.zst man completions bah.conf locale -C target/release bah

