#!/bin/sh
set -e

xtr \
	-d bah \
	--msgid-bugs-address https://github.com/Morganamilo/bah \
	--package-name=bah\
	--package-version="$(awk -F '=' '/^version/ {print $2}' Cargo.toml | sed 's/\"//g')" \
	-k printtr -k tr \
	-o=po/bah.pot \
	src/lib.rs
